version: '3'
services:
  redis:
    build: ./redis_dockers
    ports:
      - 6379:6379
  demo:
    build: ./app
    depends_on:
      - redis
    command: ['demo.py', '--redis_server', 'redis://redis:6379']
  redisinsight:
    image: redislabs/redisinsight:1.5.0
    ports:
      - "8001:8001"
  loaddbtoinsight:
    build: ./dbloader/.
    depends_on:
      - redisinsight
      - redis
    environment:
      - APP_URL=http://redisinsight:8001
    command: ['python', 'dbloader.py', "--db_urls=redis:6379"]
