version: 2.1

jobs:
  build:
    docker:
      - image: redislabs/redisai:edge-cpu-bionic
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: python3 -m pip install -r .circleci/circle_requirements.txt
      - run:
          name: Run tests
          command: python3 tests/test_demo_flow

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

workflows:
  version: 2

  default_flow:
    jobs:
      - build:
          <<: *on-any-branch
