name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout model 
      run: |
        git lfs install 
        git lfs fetch && git lfs checkout
    - name: Build the docker-compose image
      run: docker-compose up -d
    - name: Test 
      run: |
        pip install -r example_client/requirements.txt
        python example_client/client.py
      
